[project]
name = "odoo-addons-oca-l10n-usa"
version = "17.0.20240512.0"
dependencies = [
    "odoo-addon-l10n_us_form_1099>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
